/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

  @Test void HashTableTest() {
   HashTable HashFun= new HashTable();

//   Adding a key/value to your hashtable results in the value being in the data structure
    HashFun.add("John", 300);
    assertEquals(9, HashFun.hash("John"));

//    Retrieving based on a key returns the value stored
    assertEquals(300, HashFun.get("John"));

//    Successfully returns null for a key that does not exist in the hashtable
    assertEquals(null , HashFun.get("null"));

//    contains function indicating if the key exists in the table already.
    assertEquals(true , HashFun.contains("John"));
    assertEquals(false , HashFun.contains("abrar"));


  }
}
