/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }


  @Test
  void testTreeMax() {

    Node<Integer> node4 = new Node(70);
    Node<Integer> node5 = new Node(95);
    Node<Integer> node6 = new Node(110);

    Node<Integer> node2 = new Node(90, node4, node5);
    Node<Integer> node3 = new Node(120, node6, null);

    Node<Integer> root = new Node(100, node2, node3);
    BinarySearchTree binaryTree=new BinarySearchTree();

    assertEquals(120,binaryTree.maxValue(root));
  }
  @Test
  void testBreadthFirstTraverse() {
    Node<Integer> node4 = new Node(7);
    Node<Integer> node5 = new Node(8);
    Node<Integer> node6 = new Node(11);

    Node<Integer> node2 = new Node(9, node4, node5);
    Node<Integer> node3 = new Node(12, node6, null);

    Node<Integer> root = new Node(10, node2, node3);
    BinaryTree binaryTree=new BinaryTree();

    assertEquals("[10, 9, 12, 7, 8, 11]",binaryTree.breadthFirst(root).toString());
  }
  @Test
  void testFizzBuzz(){

    KTree ktree = new KTree();
    NodeK root = new NodeK("24");
    NodeK node1 = new NodeK("990");
    NodeK node2 = new NodeK("20");
    NodeK node3 = new NodeK("65");

    ktree.root = root;
    root.children.add(node1);
    root.children.add(node2);
    node1.children.add(node3);
    assertEquals("Fizz FizzBuzz Buzz Buzz ",ktree.fizzBuzz(root));
  }
}
