/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codes;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
      System.out.println(new App().getGreeting());

      int [] arr={8,4,7,18,30,15};
//      System.out.println(Arrays.toString(SortArray(arr)));
//      System.out.println(Arrays.toString(mergeSort(arr)));
      System.out.println(Arrays.toString(QuickSort.quickSort(arr,0, arr.length-1 )));


    }

}
