/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codes;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test
  void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }

  @Test
  void testSortArry() {
    SortArry sort = new SortArry();
    int[] arr = {8,4,7,18,30,15};
    int[] res = {4,7,8,15,18,30};
    assertEquals(Arrays.toString(res), Arrays.toString(SortArry.SortArray(arr)));
  }
}
