/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
@Test void addNodeTest(){

  Graph graph = new Graph();

  graph.addNode("10");
  assertEquals("[10]", graph.getNodes().toString());


}
  @Test void addedgeTest(){

    Graph graph = new Graph();

    graph.addNode("10");
    graph.addNode("1");

    graph.addEdge("10", "1");

    assertEquals("[1, 10]",graph.getNodes().toString());
    assertEquals(2, graph.size());
  }
  @Test
  public void emptyGraph(){

    Graph graph = new Graph();
    assertEquals(0,graph.size());

  }

}
