/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import treeIntersection.BinaryTree;
import treeIntersection.Node;
import treeIntersection.Tree;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


      HashTable<String, Integer> stringIntegerHashTable = new HashTable<>();
      stringIntegerHashTable.add("John", 300);
      stringIntegerHashTable.add("sanaa", 400);
      stringIntegerHashTable.add("Tom", 200);
      stringIntegerHashTable.add("Jade", 100);
      stringIntegerHashTable.add("Doa", 600);
      stringIntegerHashTable.add("Farah", 700);
      stringIntegerHashTable.add("Jason", 90000);
      stringIntegerHashTable.add("Morgan", 800);
      stringIntegerHashTable.add("Naim", 1000);
      stringIntegerHashTable.add("Qusai", 1500);
      stringIntegerHashTable.add("Deyaa", 10000);

//      System.out.println("The Integer is => " + stringIntegerHashTable.get("Jade"));
//      System.out.println("The index is => " + stringIntegerHashTable.hash("Morgan"));
//      System.out.println("Is contain ? => " + stringIntegerHashTable.contains("abrar"));
//      System.out.println("Is contain ? => " + stringIntegerHashTable.contains("Jason"));

      System.out.println(HashTable.repeatedWord("It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York..."));

      BinaryTree<Integer> firstBinaryTree = new BinaryTree<>(new Node<>(5));
      Node<Integer> node1 = new Node<>(2);
      Node<Integer> node2 = new Node<>(4);
      Node<Integer> node3 = new Node<>(1, node1, node2);
      Node<Integer> node5 = new Node<>(6);
      Node<Integer> node4 = new Node<>(5, node5, null);
      firstBinaryTree.root.right = node4;
      firstBinaryTree.root.left = node3;

      BinaryTree<Integer> secondBinaryTree = new BinaryTree<>(new Node<>(45));
      Node<Integer> node6 = new Node<>(2);
      Node<Integer> node7 = new Node<>(12);
      Node<Integer> node8 = new Node<>(1, node6, node7);
      Node<Integer> node9 = new Node<>(9);
      Node<Integer> node10 = new Node<>(5, node9, null);
      secondBinaryTree.root.right = node10;
      secondBinaryTree.root.left = node8;

//      System.out.println(Tree.treeIntersection(firstBinaryTree, secondBinaryTree));


      HashMap hashMap=new HashMap();
      hashMap.put("keyOne","1");
      hashMap.put("keyTow","2");
      hashMap.put("keyThree","3");
      hashMap.put("keyFour","4");

      HashMap hashMapTow=new HashMap();
      hashMapTow.put("keyOne","11");
      hashMapTow.put("keyTow","22");
      hashMapTow.put("keyThree","33");
      hashMapTow.put("Not exist ","");

//      System.out.println(HashTable.hashMapLeftJoinFun(hashMap,hashMapTow));

      System.out.println(isUnique("Itt twas a queer"));
//      String arr =  "Batman Thor Batman Flash Batman ";
//      FrequentWord(arr);

    }
  public static boolean isUnique(String string)
  {
    String[] words = string.toLowerCase()
      .replaceAll("[^a-z ]","").split(" ");
    for(String ch:words )
    {
      if(ch.length()==1)
      {
        return true;
      }
    }
    return false;
  }

  public static void FrequentWord(String string)
  {
    // Insert all unique strings and update count if a string is not unique.
    Map<String,Integer> hshmap = new HashMap<String, Integer>();
    String[] words = string.toLowerCase()
      .replaceAll("[^a-z ]", "")
      .split(" ");
    for (String str : words)
    {
      if (hshmap.keySet().contains(str)) // if already exists then update count.
        hshmap.put(str, hshmap.get(str) + 1);
      else
        hshmap.put(str, 1); // else insert it in the map.
    }
    // Traverse the map for the maximum value.
    String maxStr = "";
    int maxVal = 0;
    for (Map.Entry<String,Integer> entry : hshmap.entrySet())
    {
      String key = entry.getKey();
      Integer count = entry.getValue();
      if (count > maxVal)
      {
        maxVal = count;
        maxStr = key;
      }
      // Condition for the tie.
      else if (count == maxVal){
        if (key.length() < maxStr.length())
          maxStr = key;
      }
    }
    System.out.println("Most frequent word: "+ maxStr);
    System.out.println("Count: "+ maxVal);
  }
}
