/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge5;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
      App classUnderTest = new App();
      assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");

    }
  @Test void emptyList() {
    LinkedList testList = new LinkedList();
    assertEquals( "" , testList.toString() );
    assertEquals( null , testList.head );
  }

  @Test void includesTest() {
    LinkedList testList = new LinkedList();
    testList.insert(10);
    assertEquals( true , testList.includes(10) );
    assertEquals( false , testList.includes(5) );
  }

}


